name: Deploy the website

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      golive:
        description: 'Do you wish to also deploy to the live site?'
        required: false
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version to use

      - name: Install dependencies
        run: npm install
        working-directory: . # Adjust if your project directory structure is different

      - name: Build the Astro site for Staging
        env:
          PUBLIC_WP_API: ${{ secrets.PUBLIC_WP_API }}
        run: npm run build # Ensure this script exists in your package.json and builds your site into a 'dist' folder or similar

      - name: SFTP Deploy to Staging
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }} # Hostname of the SFTP server
          username: ${{ secrets.SFTP_USERNAME }} # SFTP login username
          password: ${{ secrets.SFTP_PASSWORD }} # SFTP login password
          remote_path: ${{ secrets.SFTP_DIRECTORY }} # Path on the server to deploy to
          local_path: './dist/*'

      - name: Build the Astro site for Production (Live)
        if: github.event.inputs.golive == 'true'
        env:
          PUBLIC_WP_API: ${{ secrets.LIVE_PUBLIC_WP_API }}
        run: npm run build # Ensure this script exists in your package.json and builds your site into a 'dist' folder or similar

      - name: SFTP Deploy to Production (Live)
        if: github.event.inputs.golive == 'true'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }} # Hostname of the SFTP server
          username: ${{ secrets.LIVE_SFTP_USERNAME }} # SFTP login username
          password: ${{ secrets.LIVE_SFTP_PASSWORD }} # SFTP login password
          remote_path: ${{ secrets.LIVE_SFTP_DIRECTORY }} # Path on the server to deploy to production
          local_path: './dist/*'
